name: flutter_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets\images\bike.webp
    - assets\images\dash.png
    - assets\images\jogar.jpg
    - assets\images\livro.jpg
    - assets\images\meditar.jpeg
    - assets\images\nophoto.png
    - assets\images\st,small,507x507-pad,600x600,f8f8f8.jpg
